### PR TITLE
Keep strings on top of sorting

### PR DESCRIPTION
**Pull request by wilkerlucio**
Hello!

Today I want to bring a discussion and a change proposition to the library, I've been talking with @borkdude about the `:unsorted-required-namespaces` feature, there is a issue going on in borkdude/clj-kondo too https://github.com/borkdude/clj-kondo/issues/885.

The gist is about how to sort requires that include strings. Example:

```clojure
; current-way
(:require
    [bar.core :as bar]
    ["caz" :as caz]))

; proposed way
(:require
    ["caz" :as caz]
    [bar.core :as bar]))
```

Other solutions like https://github.com/immoh/lein-nsorg or https://github.com/clojure-emacs/clojure-mode use the proposed way.

We had a guess that you used the first to follow clj-kondo conventions, but we are discussing if the second is not a better default.

What are you thoughts on it?

### CODE REVIEW

**Comment by filipesilva** [comment]
Heya @greglook, just wanted to ping you about this change. Do you think this is the sort of thing that could get in, or maybe you prefer that some changes are made to the PR?

**Comment by filipesilva** [comment]
Heya @greglook, just a friendly ping about this change again, since clj-kondo is also doing strings on top currently. Is there anything I can do to help move this along?

**Comment by greglook** [comment]
Seems like this is the established convention. :+1: I might add a configuration option for this later.

**Review by greglook — APPROVED** [review]

**Comment by filipesilva** [comment]
Sweet, thanks for the merge!

**Pull request merged**
